print("Q1")
print("The first number is: 10")
print("The second number is: 20")
print("Addition:")
print(10+20)
print("Subtraction:")
print(10-20)
print("Multiplication:")
print(10*20)
print("Division:")
print(10/20)
